kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 2
env:
  SPRING_PROFILES_ACTIVE: default, testdata, bomlo
  INNTEKTSMELDING_MANGLER_URL: https://www-gcp.dev.nav.no/syk/sykefravaer/inntektsmelding
