kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 1
cpu: 200m
memory: 400Mi
db_tier: db-f1-micro
env:
  SPRING_PROFILES_ACTIVE: default, testdata
  INNTEKTSMELDING_MANGLER_URL: https://www.ekstern.dev.nav.no/syk/sykefravaer/inntektsmelding
  INNTEKTSMELDING_MANGLER_VENTETID: 0
  KAFKA_AUTO_OFFSET_RESET: earliest
