kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 1
env:
  SPRING_PROFILES_ACTIVE: default, testdata
  INNTEKTSMELDING_MANGLER_URL: https://www-gcp.dev.nav.no/syk/sykefravaer/inntektsmelding
  INNTEKTSMELDING_MANGLER_VENTETID: 0
