kafkaPool: nav-dev
environment: dev
replicas_min: 1
replicas_max: 1
cpu: 50m
memory: 384Mi
db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
db_tempFileLimit: 1536000
azureTenant: trygdeetaten.no
external-host:
  - flex-unleash-api.nav.cloud.nais.io
env:
  SPRING_PROFILES_ACTIVE: default, testdata, forelagteopplysninger
  INNTEKTSMELDING_MANGLER_URL: https://www.ekstern.dev.nav.no/syk/sykefravaer/inntektsmelding
  FORELAGTE_OPPLYSNINGER_BASE_URL: https://www.ekstern.dev.nav.no/syk/sykefravaer/beskjed
  KAFKA_AUTO_OFFSET_RESET: earliest
  SEND_FORELAGTE_OPPLYSNINGER_FIXED_DELAY_MINUTES: 1
