apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-inntektsmelding-status
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/liveness
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  readiness:
    path: /internal/health/readiness
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 20
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 100Mi
  kafka:
    pool: {{kafkaPool}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
