kafkaPool: nav-prod
environment: prod
replicas_min: 1
replicas_max: 1
db_tier: db-custom-1-3840
env:
  SPRING_PROFILES_ACTIVE: default
  INNTEKTSMELDING_MANGLER_URL: https://www.nav.no/syk/sykefravaer/inntektsmelding
  INNTEKTSMELDING_MANGLER_VENTETID: 28
