kafkaPool: nav-prod
environment: prod
replicas_min: 1
replicas_max: 1
cpu: 600m
memory: 600Mi
db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
env:
  SPRING_PROFILES_ACTIVE: default
  INNTEKTSMELDING_MANGLER_URL: https://www.nav.no/syk/sykefravaer/inntektsmelding
  INNTEKTSMELDING_MANGLER_VENTETID: 28
  KAFKA_AUTO_OFFSET_RESET: none
