kafkaPool: nav-prod
environment: prod
replicas_min: 1
replicas_max: 1
cpu: 600m
memory: 600Mi
db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
db_tempFileLimit: 3072000
azureTenant: nav.no
env:
  SPRING_PROFILES_ACTIVE: default
  INNTEKTSMELDING_MANGLER_URL: https://www.nav.no/syk/sykefravaer/inntektsmelding
  KAFKA_AUTO_OFFSET_RESET: earliest
  MINIMUMSTID_MELLOM_FORSTE_OG_ANDRE_MANGLER_IM_VARSEL: P10D
  MINIMUMSTID_FRA_VARSEL_TIL_FORSTE_FORSINKET_SAKSBEHANDLING_VARSEL: P12D
