ALTER TABLE FORELAGTE_OPPLYSNINGER_AINNTEKT
    RENAME COLUMN FORELAGT TO STATUS_ENDRET;

ALTER TABLE FORELAGTE_OPPLYSNINGER_AINNTEKT
    ADD COLUMN STATUS TEXT;

UPDATE FORELAGTE_OPPLYSNINGER_AINNTEKT
SET STATUS = CASE
                 WHEN STATUS_ENDRET IS NULL THEN 'NY'
                 WHEN STATUS_ENDRET >= NOW() - INTERVAL '5 years' THEN 'SENDT'
    ELSE 'AVBRUTT'
END;

ALTER TABLE FORELAGTE_OPPLYSNINGER_AINNTEKT
ALTER COLUMN STATUS SET NOT NULL;
